namespace CalculateProductNumber;

using NCDK;
using NCDK.SMARTS;


public partial class SynquestPartnumberCalculator
{
    public static Dictionary<string,string> monovalentsDesc = new Dictionary<string,string>()
    {
        {"0","no H, F, Cl, Br, or I"},
        {"1","Contains H"},
        {"2","Contains F"},
        {"3","Contains F, H"},
        {"4","Contains Cl"},
        {"5","Contains Cl, H"},
        {"6","Contains Cl, F"},
        {"7","Contains Cl, F, H"},
        {"8","Contains Br"},
        {"9","Contains Br, H"},
        {"A","Contains Br, H"},
        {"B","Contains Br, F, H"},
        {"C","Contains Br, Cl"},
        {"D","Contains Br, Cl H"},
        {"E","Contains Br, Cl, F"},
        {"F","Contains Br, Cl, F, H"},
        {"G","Contains I"},
        {"H","Contains I, H"},
        {"J","Contains I, F"},
        {"K","Contains I, F, H"},
        {"L","Contains I, Cl"},
        {"M","Contains I, Cl, H"},
        {"N","Contains I, Cl, F"},
        {"P","Contains I, Cl, F, H"},
        {"R","Contains I, Br"},
        {"S","Contains I, Br, H"},
        {"T","Contains I, Br, F"},
        {"U","Contains I, Br, F, H"},
        {"V","Contains I, Br, Cl"},
        {"W","Contains I, Br, Cl, H"},
        {"X","Contains I, Br, Cl, F"},
        {"Y","Contains I, Br, Cl, F, H"}
    };
    public static Dictionary<string,string> fgDesc = new Dictionary<string,string>() 
    {
        {"EE","Error in calculation"},
        {"00","No functional group"},
        {"01","Primary Alchohols | Phenols"},
        {"02","Secondary Alchohols"},
        {"03","Tertiary Alchohols"},
        {"04","Diols"},
        {"05","Polyols"},
        {"06","Hemi(acetal | ketal)"},
        {"07","Ethers"},
        {"08","Polyethers | Acetals | Ketals"},
        {"09","Epoxides"},
        {"10","Cyclic ethers"},
        {"11","Crown ethers"},
        {"12","Carbohydrates"},
        {"13","Hypophalites"},
        {"14","Peroxides | Oxonium"},
        {"15","Aldehydes"},
        {"16","Acid halides"},
        {"17","Ketones"},
        {"18","Polycarbonyls"},
        {"19","Ketenes"},
        {"20","Hydroxy Ketones"},
        {"21","Carboxylic Acids"},
        {"22","Carboxylates"},
        {"23","Esters"},
        {"24","Unsaturated esters"},
        {"25","Lactones"},
        {"26","Anhydrides"},
        {"27","Peroxyacids"},
        {"28","Carbonates"},
        {"29","Keto-acids/ester | Hydroxy-acid/ester"},
        {"30","Primary amines"},
        {"31","Secondary amines"},
        {"32","Tertiary amines"},
        {"33","Ammonium"},
        {"34","Aziridines"},
        {"35","Imines"},
        {"36","Enamines | Ketenamines"},
        {"37","Nitriles | Isonitriles"},
        {"39","Hydrazines | Hydrazones"},
        {"40","Diazenes"},
        {"41","Amidines | Guanidines"},
        {"42","Azides"},
        {"43","Purines"},
        {"45","Nitroso | Nitroxide"},
        {"46","Cyanohydrin | Acyl cyanide"},
        {"47","Oximes | Hydroxylamines"},
        {"48","Amide | Lactam | Amino ketones"},
        {"49","Cyanate | Isocyanate"},
        {"50","Nitrones | Nitrile oxides | Amine oxides"},
        {"52","Nitrosoamine | Diazene oxide"},
        {"53","Ureas | Uracil"},
        {"54","Nitro"},
        {"55","Nitro amines | Amides | Nitriles"},
        {"56","Carbamic acid | Carbamates | Hydrazide | O-C-N"},
        {"57","Amino Acids and their salts"},
        {"58","Amino Acid derivatives"},
        {"59","Nucleosides"},
        {"60","Organoboron | Organic borate | Lewis adducts | Organic borate salts"},
        {"61","Thiols | Thiophenols"},
        {"62","Sulphenyl | Sulfinyl | Sulfonyl Halides"},
        {"63","Sulfonyloxy | Sulfones"},
        {"65","Sulfinate | Sulfoxide"},
        {"64","Sulfoantes | Sulfates"},
        {"66","Sulfides | Disulfides | Polysulfides"},
        {"67","Thiocarbonyl | Thiocarboxy | Thiamide | Thiourea"},
        {"68","Thiocyanate | Isothiocyanate"},
        {"69","Sulfonamide | Sulfonimide | Amino-sulfur"},
        {"70","Sulfure & other heteroatom heterocyclics"},
        {"71","Sulfur Halides"},
        {"72","Phosphines"},
        {"73","Halophosphines"},
        {"74","Phosphite | Phosphine oxide"},
        {"75","Phosphates"},
        {"76","Phosphonium"},
        {"77","Phosphonate"},
        {"78","Phosphorus ylide | Phosphorane"},
        {"79","Phosphazene | Phosphoramide"},
        {"80","Silanes"},
        {"81","Halosilanes"},
        {"82","Silanol"},
        {"83","Alkoxysilanes"},
        {"84","Aryloxysilane"},
        {"85","Siloxane"},
        {"86","Silane ester"},
        {"87","Amino silanes"},
        {"88","Silazane"},
        {"89","(Amido | Imino | Ketoximino) silanes"}
    };
    public static Dictionary<string,string> structureDesc = new Dictionary<string,string>()
    {
        {"0","Non-carbonaceous"},
        {"1","Alkanes"},
        {"2","Cycloalkanes"},
        {"3","Alkenes"},
        {"4","Cycloalkenes"},
        {"5","Alkynes"},
        {"6","Aromatics"},
        {"7","Aryl alkanes"},
        {"8","Aryl trifluoromethyl"},
        {"9","Aryl (alkenes | alkynes)"},
        {"H","Heterocyclic"}
    };
    public static Dictionary<string,string> polyvalentsDesc = new Dictionary<string, string>()
    {
        {"1","Contains Carbon only"},
        {"2","Contains Carbon and Oxygen"},
        {"3","Contains Carbon and Nitrogen"},
        {"4","Contains Carbon and Nitrogen and Oxygen"},
        {"5","Contains Carbon and other(s)"},
        {"6","Contains Carbon and Oxygen and other(s)"},
        {"7","Contains Carbon and Nitrogen and other(s)"},
        {"8","Contains Carbon and Nitrogen and Oxygen and other(s)"},
        {"9","Organometallics"},
        {"M","Inorganics"},
    };
}